workflows:
  ios-testflight:
    name: Build iOS and publish to TestFlight
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple-credentials
      vars:
        BUNDLE_ID: "com.ygor.notificacoesapp"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: "ygor1158@hotmail.com"
        app_specific_password: Encrypted(APP_SPECIFIC_PASSWORD)
        team_id: "48774VJ75X"
        bundle_id: "com.ygor.notificacoesapp"
        submit_to_testflight: true
